### ISSUE TITLE
Working directory gets polluted with `*.mps` files

### ISSUE THREAD

**Issue by fmannhardt** [process-intelligence-solutions/pm4py#131]
Version: PM4Py 1.2.6 (release)
OS: Windows 10
Python: 3.7.4

Trying to use alignments, for example, as in the documentation:
https://pm4py.fit.fraunhofer.de/documentation#item-5-2

I noted that for each run the current working directory gets polluted with files in the form:
`e4a2928e287243b99f1be6a647d5390e-pulp.mps`
This seems to be an optimisation problem solved.

This behaviour is annoying and could cause issue when the current working directory is not writable. I would suggest to move these files to a temporary folder that gets cleaned up.

**Comment by fit-alessandro-berti** [comment]
Dear Felix,

Thanks for signaling.

Actually, there has been a major release of PuLP (2.0). With that release, on my computer everything still works well, but I guess this could be related to your problems. You can try to downgrade PuLP to the 1.6.10 and see if it changes.

Anyhow, the Ortools should now be the default solver for all the platforms except win32, because it is faster than PuLP. It should be installed automatically within the PM4Py installation (but in your case is not). You can try to install Ortools with doing pip install -U ortools

Talking about faster solvers, you would need to install the package pm4pycvxopt, and import it as first row of your scripts, if you wish to use the CVXOPT solver. You can follow the documentation for that

**Comment by fmannhardt** [comment]
See in the other issue, solved when installing `ortools`.
