### ISSUE TITLE
No module named 'pm4py.algo.other'

### ISSUE THREAD

**Issue by hristochr** [process-intelligence-solutions/pm4py#134]
I am attempting to make a cluster analysis. The import statement:

`from pm4py.algo.other.conceptdrift.utils import get_representation`
returns the following error: 

`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-54-50977e618a0e> in <module>()
----> 1 from pm4py.algo.other.conceptdrift.utils import get_representation
      2 
      3 clf, feature_names, classes = get_representation.get_decision_tree(clusters[0], clusters[1])

ModuleNotFoundError: No module named 'pm4py.algo.other'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
`
Can you advise please?

**Comment by fit-alessandro-berti** [comment]
Dear hristochr,

Actually the conceptdrift has been moved to a different package.

You could retrieve it by installing pm4pyclustering from Pypi (pip install -U pm4pyclustering)

Then the commands are the same, but instead of PM4Py you need to use PM4PyClustering, example:

from pm4pyclustering.algo.other.conceptdrift.utils import get_representation

Sincerely
Alessandro
