### ISSUE TITLE
Obtain Top K Traces with Conditionals

### ISSUE THREAD

**Issue by seanlaw** [process-intelligence-solutions/pm4py#139]
Let's say we have a few billion traces, is there a way to obtain the, say, top 50 traces by frequency? 

Additionally, I require that:

1. The traces must be greater than some length `M`
2. The traces must have state/process `S` at the `Mth` position in the trace (so traces that are longer than `M` are extracted into sub traces by using a sliding window of length `M`)

Can this be done simultaneously for varying `S`, `M`, and `N` without having to run through the data again?

**Comment by fit-alessandro-berti** [comment]
Dear Sean,

Generally you could obtain the dictionary of variants by applying the method pm4py.algo.filtering.log.variants.variants_filter.get_variants
This dictionary has as key the variant and as value the list of cases following that variant.
You can retrieve the length of this list for each key, and populate a list of tuples of length 2 (where the first element is the variant, and the second element is the count). Then, you can apply a sort operation to these.

If you need to perform the other two points, I suggest to memorize the variant as a tuple of elements (currently the variant is a string, so you can split by , ). Then, it is easy to check also the length of the variant or the element at position X

We are not going to implement the two points in the main library, since they seem a bit ad-hoc ;) but it's easy with a bit of Python code to do them
