### ISSUE TITLE
How to use this code on version 1.3.0

### ISSUE THREAD

**Issue by serkserk** [process-intelligence-solutions/pm4py#165]
Hi, this is the code I used to work with version <1.3.0 but I can't make it work on version 1.3.0

```
from pm4py.algo.discovery.dfg import factory as dfg_factory
from pm4py.objects.heuristics_net import net as heuristic_net
def testFunc(log):
    dfg_freq = dfg_factory.apply(log)
    freq_heu_net = heuristic_net.HeuristicsNet(dfg_freq)
    freq_heu_net.calculate(dependency_thresh=-1)

    dfg_perf = dfg_factory.apply(log, variant="performance")
    perf_heu_net = heuristic_net.HeuristicsNet(dfg_freq, performance_dfg=dfg_perf)
    perf_heu_net.calculate(dependency_thresh=-1)

    return [freq_heu_net, perf_heu_net]

print( testFunc(log)[0].performance_matrix )
```

Trying this code to get the performance variant fail:
and give me this error: 

> TypeError: unsupported operand type(s) for -: 'str' and 'str'

```
from pm4py.algo.discovery.dfg import algorithm as dfg_discovery
from pm4py.objects.heuristics_net import net as heuristic_net
def testFunc(log):
    dfg_freq = dfg_discovery.apply(log)
    freq_heu_net = heuristic_net.HeuristicsNet(dfg_freq)
    freq_heu_net.calculate(dependency_thresh=1)

    dfg_perf = dfg_discovery.apply(log, variant=dfg_discovery.Variants.PERFORMANCE)
    perf_heu_net = heuristic_net.HeuristicsNet(dfg_freq, performance_dfg=dfg_perf)
    perf_heu_net.calculate(dependency_thresh=1)

    return [freq_heu_net, perf_heu_net]
```

**Comment by Javert899** [comment]
Dear Serkserk,

The problem lies in your time:timestamp attribute.
At least for some event, it must be a string

Please double check the XES log.
If you start from a CSV log, make sure that the datetime columns are casted before the conversion to event log. Just look at this code snippet:

import pandas as pd
from pm4py.objects.log.util import dataframe_utils
from pm4py.objects.conversion.log import converter as log_converter

log_csv = pd.read_csv('<path_to_csv_file.csv>', sep=',')
log_csv = dataframe_utils.convert_timestamp_columns_in_df(log_csv)
log_csv = log_csv.sort_values('<timestamp_column>')
event_log = log_converter.apply(log_csv)

**Comment by serkserk** [comment]
Thanks, that did the trick !
