### ISSUE TITLE
Median for average arrival rate for an event log

### ISSUE THREAD

**Issue by shubhambalyan** [process-intelligence-solutions/pm4py#200]
Hi,

While trying to calculate the average arrival rate for an event log, we saw that for some real-life and large event logs, the average arrival rate is returned as 0 seconds. After going through the code at this location "pm4py/statistics/traces/log/case_arrival.py" in the git repo, we realized that instead of the mean, the code is returning the median of the case arrival times. 

Although we know that the statistic measure 'median' is robust to outliers, an average arrival rate of 0 seconds is not so intuitive.  That just says that all of the traces arrived at the same time in the process, which is obviously not the case with a real-life event log. We tried modifying the code and got a real value in seconds if we return the mean of the case arrival times.

Any specific reason as to why 'median' is used instead of 'mean'?

Thanks.

**Comment by fit-alessandro-berti** [comment]
Hej,

Using the "median" helps in other points to avoid considering outliers (for example, in the performance of a path).

However, as you point out, for the case arrival it does not really make sense to use the "median" instead of the "mean". It also adds an incongruency, because the case arrival utility on Pandas dataframes returns the mean, while on logs it returns the median.

We will consider to fix this in the next release

Thanks! Sincerely

**Comment by fit-sebastiaan-van-zelst** [comment]
this will be fixed in pm4py 2.1.4.1 which we will release in a few minutes
