### ISSUE TITLE
Log parsing speed has dropped significantly

### ISSUE THREAD

**Issue by iliam** [process-intelligence-solutions/pm4py#215]
I have different "log.xes" file with 2700-2900 traces (Size: 55 - 65 Mb). I run the below code:

- net, initial_marking, final_marking = inductive_miner.apply(log, parameters={"NOISE_THRESHOLD": 0.2})

Until the version 2.1.1, the speed of "log parsing, completed traces ::"  was high (400-500 it/s). After 2.1.1, the speed has dropped dramatically (5-20 it/s).
I wonder if we could investigate the reason.

**Comment by fit-alessandro-berti** [comment]
Dear iliam,

From those versions, we started revising heavily the log importing mechanism:
- A slightly more time consuming XES importer is the default, which produces a much lower (approx 50%) memory occupation
- The reading of log files in .xes.gz happens directly from the .xes.gz file not by uncompressing the file.

As your issue, we conducted some tests to see if regressions occurred. The environment of the tests is Python 3.8 on Windows 10 with the latest upgrades. The time measured are from the start of the importing (before the progress bar appears) to when the import finishes. Some popular logs are used.


  | PM4Py 2.2.4 |   | PM4Py 2.1.0 |  
-- | -- | -- | -- | --
  | .xes | .xes.gz | .xes | .xes.gz
bpic2012 | 13,17 | 13,53 | 12,14 | 13,91
bpic2017 | 18 | 17,1 | 15,08 | 18,8
bpic2017_application | 79,08 | 80,63 | 72,38 | 83,74
bpic2019 | 111,14 | 110,1 | 106,94 | 118,42
Billing | 33,08 | 35,75 | 35,05 | 40,8

Yes, there has been a slight regression (5%-10%) in the importing speed due to the new variant but the memory footprints of the log is 50% lower, so is a trade off.
Moreover, you can notice the improvement in importing the .xes.gz files against the older version.

As I was not really able to reproduce your issue, could you point me more about your working environment (version of Python? operating system? version of LXML)?
.

**Comment by iliam** [comment]
Thank you for replying. I am using:
- python 3.8
- windows 10
- LXML 4.6.1
I tried another time with both versions. The result is the same as I mentioned. I tried on python 3.7 as well. XES file is 64 Mb. I can send you the .xes file privately or take a video of the two versions.

**Comment by fit-alessandro-berti** [comment]
Thanks

We will further investigate the issue and if we cannot find the root cause we will contact you

I have some hyphotesis in mind that will be tested

**Comment by fit-alessandro-berti** [comment]
My hyphotesis on your degradation were:
- extraordinary number of different attributes
- extraordinary length of the string attributes values that are in your log
- many different dates in the log
I tested all of these hyphotesis but could not find the degradation. At this point, I would ask you to check with the following code:

import pm4py
from pm4py.objects.log.importer.xes import importer as xes_importer
import time

aa = time.time()
log = xes_importer.apply("aaa.xes", variant=xes_importer.Variants.ITERPARSE)
bb = time.time()
print(bb-aa)
log = xes_importer.apply("aaa.xes", variant=xes_importer.Variants.ITERPARSE_MEM_COMPRESSED)
cc = time.time()
print(cc-bb)


If the 'old' importer (ITERPARSE) is faster on your log than the 'new' importer (ITERPARSE_MEM_COMPRESSED)

Let me know

**Comment by iliam** [comment]
Thank you for your quick reply. I just tested.

xes_importer.Variants.ITERPARSE is done in 8.7 seconds. This is just like pm4py 2.1.1 and before (450 - 550 it/s)
xes_importer.Variants.ITERPARSE_MEM_COMPRESSED takes forever ( ~45 minutes) :)

For the .xes file, I think you are correct. 2900 traces and the number of attributes and dates are pretty big. (not sure if extraordinary big)

![pm4py speed test](https://user-images.githubusercontent.com/13187974/114076214-086a3480-986c-11eb-9408-e5819a06a49a.png)

**Comment by iliam** [comment]
Hey, Did you have a chance to look at this issue?

**Comment by fit-alessandro-berti** [comment]
Dear iliam,

We closed the problem by making ITERPARSE the default variant

So now the default methods in PM4Py should work fine with your log
