### ISSUE TITLE
Missing Parameter

### ISSUE THREAD

**Issue by hb237** [process-intelligence-solutions/pm4py#264]
Since my log does not follow the Concept Extension as defined in the [XES Standard](https://xes-standard.org/_media/xes/xesstandarddefinition-2.0.pdf) I am using custom parameters to configure the filter. 

For the context: I have a process log that describes processes running on a blockchain application, hence the parameters _from_block_ and _to_block_ or the attribute key _tx_blocknumber_ in the snippet below. The parameters CASE_ID_KEY, ATTRIBUTE_KEY and POSITIVE work all fine. However, I have to unset the standard _case_attribute_prefix_.

Currently I simply write the constant string, as it is defined as CASE_ATTRIBUTE_PREFIX in the file pm4py/objects/conversion/log/variants/to_event_log.py. For sure I could import this constant, but I kindly recommend this constant to be part of pm4py/algo/filtering/log/attributes/attributes_filter.py else it is difficult to find and bit hard to understand.

```
def get_petri_net(from_block, to_block):
    log = xes_importer.apply("my/path/to/log.xes")
    filtered_log = attributes_filter.apply_numeric(log, from_block, to_block, 
        parameters={'case_attribute_prefix': '',
                    attributes_filter.Parameters.CASE_ID_KEY: 'ident:piid',
                    attributes_filter.Parameters.ATTRIBUTE_KEY: 'tx_blocknumber',  
                    attributes_filter.Parameters.POSITIVE: True})
    net, initial_marking, final_marking = inductive_miner.apply(filtered_log)
    pm4py.view_petri_net(net, initial_marking, final_marking, format='png') 
```

**Comment by fit-alessandro-berti** [comment]
Dear hb237,

Thanks for signaling this.

The conversion from event log to event stream adds a prefix (by default "case:") in front of all the case attributes (to separate them from the attributes at the event level). Actually, in the considered piece of code, the "case:" is hardcoded (no possibility to provide a different prefix).

We will come up with a solution for this in the next release. We could not directly accept your MR, because it removes completely the addition of the prefix.

**Comment by hb237** [comment]
Thank you!
