### ISSUE TITLE
Problem with Process discovery and conformance checking

### ISSUE THREAD

**Issue by stamik1** [process-intelligence-solutions/pm4py#267]
Hello, everyone,
I have a log indicating a sequence of activities that a person has to do on a daily basis and I use this log to calculate the Petri net and thus rightly obtain a linear net.
I then created another log, similar to the one for the model, but which repeats the same activities daily in the same sequence as the model.
As columns I have: case_id which has a different value every day, timestamp, activity and the respective value.

I would like to know why when I do the process discovery on the log where I have replicated the same trace several times I get a different petri net than when I do it with the log with only one trace?

Also, I calculated the fitness with token based replay and I noticed that I get all 1.0 values since the log is the same as the model, but only one trace changes where I skip an activity, even though it is written correctly in the log. I would like to understand the reason for this.

I thank you for your help.

**Comment by fit-alessandro-berti** [comment]
Dear stamik,

The issue is strange, but please provide more information (e.g. which process discovery algorithm are you using, if the data is sorted ...). Code snippets would help a lot to identify the issue. Also, please tell us the version of PM4Py that you are using.

For the conformance question, I do not really understand it. Could you exemplify what happens?
