### ISSUE TITLE
ISO8601 strings not fully supported with strpfromiso for Python versions below 3.11

### ISSUE THREAD

**Issue by johannesmols** [process-intelligence-solutions/pm4py#385]
Hi, I just stumbled into an issue with date parsing while reading an OCEL file with the following timestamp format: `2023-02-08T12:42:31.4525748+01:00`. The error is the following: `Invalid isoformat string`, and is a general limitation with Python versions below 3.11, as discussed [here](https://stackoverflow.com/q/55542280/2102106).

I have looked through the code and there is already an alternative `ciso8601`, which is only activated when the package is installed. For any Python versions above 3.7 however, the default [fromisoformat](https://docs.python.org/3/library/datetime.html?highlight=fromisoformat#datetime.datetime.fromisoformat) is used, even if `ciso8601` is installed. The dependency on `ciso8601` was also removed in version [2.2.19](https://github.com/pm4py/pm4py-core/releases/tag/2.2.19).

While the default Python implementation works fine in most cases, not everything is supported between 3.7 and 3.10. A solution is of course to upgrade to Python 3.11, but that is not immediately obvious from the error message.

Might I suggest adding a warning of some kind when using a Python version below 3.11? So that it is easy to see what is wrong when encountering the issue. Although that would probably show the warning to everyone, even if they won't encounter the issue. Alternatively, the dependency on `ciso8601` could be added back in like so: `ciso8601; python_version < '3.11`. Another alternative is `python-dateutil`, which is discussed [here](https://stackoverflow.com/a/15228038/2102106).

I'm willing work on a PR to adjust this and set the default parser according to the Python version, but I would like to hear your opinion first what the best approach would be.

**Comment by fit-alessandro-berti** [comment]
We preferred the strpfromiso over ciso8601 because the latter is a package that requires compilation, therefore the Visual Studio C++ environment needs to be installed in Windows (admittely Linux is problematic)

We also could consider python-dateutil, in particular I saw the parser.parse method in action, but I would prefer not to insert another dependency doing the same trick.

Morale: we could use ciso8601 as default if installed. Otherwise, trigger a warning if the version of Python is lower than 3.11 and strpfromiso is used. I will push that asap

**Comment by johannesmols** [comment]
Looks great, I think that's a good compromise!
