### ISSUE TITLE
Dependence on Graphviz software

### ISSUE THREAD

**Issue by fpjaa** [process-intelligence-solutions/pm4py#425]
Hello, I'd like to know if there's any way to remove the dependence on the Graphviz software in order to have the graph visualizations in Python. The Graphviz library doesn't have the executables (so downloading the software separately is required) and I'm curious about finding a way to use other libraries that don't require downloading software that will allow to visualize the PM4PY maps and other plots. Thank you.

**Comment by fit-alessandro-berti** [comment]
Yes Graphviz is usually used in pm4py as external binary dependency that you could install (on Windows) from the Graphviz website.

However, we also offer support for GraphvizJS which can be used in most visualizations providing format='html'

For example,

pm4py.view_dfg(dfg, start_activities, end_activities, format='html')

In this case, no binary Graphviz is needed because the rendering is done by a Javascript library in the HTML page.
