### ISSUE TITLE
Format handeling

### ISSUE THREAD

**Issue by JazminADiaz** [process-intelligence-solutions/pm4py#430]
In the previous versions I was able to generate models using only seconds in the time column, however now I keep getting the error "Exception: the dataframe should (at least) contain a column of type date". I do not have the dates, just seconds, do I have to make up a date, and if so, in what format?

**Comment by fit-alessandro-berti** [comment]
Assuming that your seconds represent the time elapsed since a specific date, such as the Unix epoch (1970-01-01), you can convert a pandas column of seconds into a datetime column as follows:

import pandas as pd

# Assume df is your DataFrame and 'seconds' is your column of seconds

df['datetime'] = pd.to_datetime(df['seconds'], unit='s')


Note that pd.to_datetime() will convert the number of seconds from the Unix epoch (1970-01-01). If your seconds are from a different starting point, you would need to adjust the 'origin' parameter accordingly.

For example, if your seconds were from the start of the year 2000, you could do:

df['datetime'] = pd.to_datetime(df['seconds'], unit='s', origin='2000-01-01')
